#ifndef MUGEN_SELECTORTYPE_H
#define MUGEN_SELECTORTYPE_H
enum class SelectorType {
    FUNCTION,
    OSCILLATOR,
    WAVETYPE,
    INTEGER,
    FINEDOUBLE,
    DOUBLE
};
#endif //MUGEN_SELECTORTYPE_H
